# Generated by Django 2.0 on 2018-09-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('standard', models.CharField(max_length=30)),
                ('change_dollar', models.CharField(max_length=30)),
            ],
        ),
    ]
